### ISSUE TITLE
Expect not empty string

### ISSUE THREAD

**Issue by saintdron** [xparse/ElementFinder#114]
ElementFinder does not create an object if the first argument is an empty string and constructor throws 'Expect not empty string'.

**Comment by funivan** [comment]
I can not reproduce this code. Can you give more details?

**Comment by saintdron** [comment]
new ElementFinder('') throw Exception (see src/ElementFinder.php:78)

**Comment by funivan** [comment]
And why should we change this behavior? What problem does it solve?

**Comment by funivan** [comment]
We can remove exception and prepare ElementFinder to work with empty documents. Waiting for PR

**Comment by funivan** [comment]
Done.
