### ISSUE TITLE
broken PhpDoc

### ISSUE THREAD

**Issue by ChrisGalliano** [xparse/ElementFinder#12]
BaseCollection.php

getLast, getFirst, getNext and getPrevious return "mixed" (in PhpDoc), so PhpStorm can't give you a hint, when you call "->".

**Comment by funivan** [comment]
@ChrisGalliano can you make PR ?

**Comment by ChrisGalliano** [comment]
@funivan yep :)

**Comment by funivan** [comment]
@sevikerr fix some bugs. @ChrisGalliano check all php doc comments and fix them.
