### ISSUE TITLE
Create extractors and simplify classes

### ISSUE THREAD

**Issue by funivan** [xparse/ElementFinder#69]
Maybe it would be better to create some Extractors. For example
```php
#1 Key Value method
ElementFInder::keyValue($keyExpression, $valueExpression)
(new KeyValueExtractor($page))->extract($keyExpression, $valueExpression)

#2. Form Helper convert to class
(new FormDataExtractor($page))->extract($expression)

# 3 Attributes
ElementCollection::getAttributes 
(new AttributesExtractor())->extract($nodeList)

#4 Make another way to extract outer content
ElementFInder::content($expression, true)
StringCollection::createWithOuterContent(\DomNodeList $items)

#5 simple way to fetch values (if needed)
ElementFInder::value($expression, true)
StringCollection::createWithValue(\DomNodeList $items)


```

**Comment by funivan** [comment]
@ganchclub ping. What do you think? What we really need and which methods can be dropped.

**Comment by funivan** [comment]
@ganchclub ping.

**Comment by ganchclub** [comment]
I don't think we need Extractors for value and outer content as well as attributes. 
Form data can be extracted in helper method. 
keyValue() is very easy to use it on ElementFinder object (IDE will also help you to choose needed method)
`$page->keyValue($keyExpression,$valueExpression);`

IMO, It's uncomfortable to pass ElementFinder to other objects, as these are the key methods in library.

**Comment by funivan** [comment]
1. Is it hard to use `FormHelper` ?  Would it be better to have all `helper` methods in ElementFinder?
For example `ElementFinder::getFormData`
2. What methods we can totally remove?
3. What methods we really need: content, value, keyValue .... what else?
